### ISSUE TITLE
All searche sreturn only 7 links

### ISSUE THREAD

**Issue by jaum20** [manutorrente/SearchML#4]
Irrespective to the search parameters used, the SearchML.py script will return only 7 links:
![teste](https://user-images.githubusercontent.com/36702273/134938387-0f3a425b-c106-4233-b0f2-8d991dd268f9.png)

I have tried different values to "num_pages", bit the problem stills the same

**Comment by manutorrente** [comment]
It's set up to return a max of 7 publications per item. If you want to change it, edit or remove the `[0:7]` in 
`  self.final_results = sorted(filtered_results, key=lambda result: result["price"])[0:7] #limits amount of results` in the ClassML code.
